name: Android - PlayStore

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Select the environment
        options:
        - staging
        - production
        
jobs:
  deploy-playstore:
    runs-on: ubuntu-latest

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: app-release-${{ inputs.choice }}
        github-token: ${{ secrets.TOKEN_GITHUB }}
        repository: Vhalia/EdunionApp
        run-id: ${{ github.event.workflow_run.id }}

    - name: LS
      run: ls -a
        
    - name: Upload to Play Store
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJson: ${{ secrets.PLAY_STORE_JSON_KEY }}
        packageName: org.edunionapp
        releaseFiles: app-release.aab
        track: internal  # Can be internal, alpha, beta, or production
        status: completed
        # Optional: Release notes for each language
        # whatsNewDirectory: distribution/whatsnew
        # mappingFile: android/app/build/outputs/mapping/release/mapping.txt
