name: IOS CD AppStore

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Select the environment
        options:
        - production

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: macos-15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install node modules
      run: npm i

    - name: Install CocoaPods dependencies
      run: |
        cd ios
        sudo gem install cocoapods
        pod install --repo-update
        cd ..

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true

    - name: Install fastlane
      run: brew install fastlane

    - name: Build iOS app
      run: |
        cd ios
        fastlane build

    - name: Deploy to TestFlight
      run: |
        cd ios
        fastlane release
      env:
        APP_STORE_CONNECT_API_KEY: ${{ secrets.IOS_APP_STORE_CONNECT_API_KEY }}
