name: IOS CD AppStore

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Select the environment
        options:
        - production

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: macos-15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install node modules
      run: npm i

    - name: Install CocoaPods dependencies
      run: |
        cd ios
        sudo gem install cocoapods
        pod install --repo-update
        cd ..

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true

    - name: Install fastlane
      run: brew install fastlane

    - name: Import Provisioning Profile
      env:
        DATA: ${{ secrets.IOS_MOBILEPROVISION_APPSTORECONNECT }}
      run: echo $DATA | base64 -di >> ios/EdunionAppStoreConnect.mobileprovision
    
    - name: Import Certficate P12
      env:
        DATA: ${{ secrets.IOS_P12 }}
      run: echo $DATA | base64 -di >> ios/DistributionCertificate.p12

    - name: Install Code Signing Assets
      run: |
        # Create keychain
        security create-keychain -p Max.1234 build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p Max.1234 build.keychain
    
        # Import certificate
        security import ios/DistributionCertificate.p12 \
          -k build.keychain \
          -P ${{ secrets.IOS_CERTIFICATE_PASSWORD }} \
          -T /usr/bin/codesign
    
        # Install provisioning profile
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp ios/EdunionAppStoreConnect.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
    
    - name: Deploy to TestFlight
      run: |
        cd ios
        fastlane releasetestflight
      env:
        APP_STORE_CONNECT_API_KEY: ${{ secrets.IOS_APP_STORE_CONNECT_API_KEY }}
