name: IOS CD AppStore

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Select the environment
        options:
        - production

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: macos-15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install node modules
      run: npm i

    - name: Install CocoaPods dependencies
      run: |
        cd ios
        sudo gem install cocoapods
        pod install --repo-update
        cd ..

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true

    - name: Install fastlane
      run: brew install fastlane

    #- name: Import Certficate P12
    #  env:
    #    DATA: ${{ secrets.IOS_P12 }}
    #  run: echo $DATA | base64 --decode > ios/DistributionCertificate.p12

    #- name: Import Provisioning Profile
    #  env:
    #    DATA: ${{ secrets.IOS_MOBILEPROVISION_APPSTORECONNECT }}
    #  run: echo $DATA | base64 --decode > ios/EdunionAppStoreConnect.mobileprovision

    - name: Configure XCode
      run: |
        cd ios
        fastlane configuresigning
      env:
        APP_STORE_CONNECT_API_KEY: ${{ secrets.IOS_APP_STORE_CONNECT_API_KEY }}
        TEAM_ID: NDWYDXTJLH
        PROFILE_NAME: Edunion App Store Connect

    - name: Import Profile and Certificate
      run: |
        cd ios
        fastlane setupcodesigning
      env:
        KEYCHAIN_PWD: Max.1234
        CERT_PWD: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
        MOBILEPROVISION_PROFILE_B64: ${{ secrets.IOS_MOBILEPROVISION_APPSTORECONNECT }}
        CERTIFICATE_B64: ${{ secrets.IOS_P12 }}
    
    - name: Deploy to TestFlight
      run: |
        cd ios
        fastlane releasetestflight
      env:
        APP_STORE_CONNECT_API_KEY: ${{ secrets.IOS_APP_STORE_CONNECT_API_KEY }}
        PROFILE_NAME: Edunion App Store Connect
