name: IOS - CD

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Select the environment
        options:
        - staging
        - production

jobs:
  build-ios:
      runs-on: macos-12

      steps:
      - uses: actions/checkout@v3

      - name: TEST
        run: echo ${{ secrets.IOS_GOOGLESERVICEINFO_PLIST }}

      - name: Load Google Service file
        env:
          DATA: ${{ secrets.IOS_GOOGLE_SERVICE }}
        run: echo $DATA | base64 -di > ios/GoogleService-Info.plist

      - name: Install node modules
        run: npm i

      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Restore Pods cache
        uses: actions/cache@v3
        with:
          path: |
            ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install pod dependencies
        run: cd ios && pod install && cd ..

      - name: Build iOS (Release)
        uses: yukiarrr/ios-build-action@v1.5.0
        with:
          project-path: ios/EdunionApp.xcodeproj
          p12-base64: ${{ secrets.IOS_P12 }}
          mobileprovision-base64: ${{ secrets.IOS_MOBILEPROVISION_ADHOC }}
          code-signing-identity: "Apple Distribution"
          certificate-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          team-id: ${{ secrets.IOS_TEAM_ID }}
          workspace-path: ios/EdunionApp.xcworkspace
          output-path: "EdunionApp.ipa"

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: "EdunionApp.ipa"
          path: "EdunionApp.ipa"
