name: Android - CD

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Select the environment
        options:
        - staging
        - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install node modules
      run: npm i
    
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
        
    - name: Load Google Service file
      env:
        DATA: ${{secrets.GOOGLE_SERVICES_JSON}}
      run: echo $DATA | base64 -di > android/app/google-services.json

    - name: Load Android Keystore
      env:
        DATA: ${{secrets.ANDROID_KEYSTORE}}
      run: echo $DATA | base64 -di > android/app/edunion-key.keystore

    - name: Prepend Android Keystore credentials to gradle.properties
      env:
        DATA: ${{secrets.ANDROID_KEYSTORE_CREDENTIALS}}
      run: echo $DATA | base64 -di >> android/gradle.properties
      
    - name: Add rights to gradlew
      run: chmod +X android/gradlew
    
    - name: Build release for staging
      if: ${{ inputs.choice }} == 'staging'
      run: npm run android:release:staging
      
    - name: Build release for production
      if: ${{ inputs.choice }} == 'production'
      run: npm run android:release
      
    - name: Upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        groups: Testers
        file: android/app/build/outputs/apk/release/app-release.apk
