name: IOS - CD Firebase

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Select the environment
        options:
        - staging
        - production

jobs:
  build:
      runs-on: macos-15

      steps:
      - uses: actions/checkout@v4

      - name: Install node modules
        run: npm i

      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Restore Pods cache
        uses: actions/cache@v3
        with:
          path: |
            ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install pod dependencies
        run: cd ios && pod install && cd ..

      - name: Build iOS (Release)
        uses: yukiarrr/ios-build-action@v1.12.0
        with:
          project-path: ios/EdunionApp.xcodeproj
          p12-base64: ${{ secrets.IOS_P12 }}
          mobileprovision-base64: ${{ secrets.IOS_MOBILEPROVISION_ADHOC }}
          code-signing-identity: "Apple Distribution"
          export-method: "ad-hoc"
          certificate-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          team-id: ${{ secrets.IOS_TEAM_ID }}
          workspace-path: ios/EdunionApp.xcworkspace
          output-path: "EdunionApp.ipa"
          increment-build-number: true

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: EdunionApp-${{ inputs.choice }}
          path: "EdunionApp.ipa"

  deploy-testers:
      needs: build
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4
        - uses: actions/download-artifact@v4
          with:
            name: EdunionApp-${{ inputs.choice }}
  
        - name: Upload artifact to Firebase App Distribution
          uses: wzieba/Firebase-Distribution-Github-Action@v1
          with:
            appId: ${{secrets.FIREBASE_APP_ID_IOS}}
            serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
            groups: Testers
            file: EdunionApp.ipa
            releaseNotes: ${{ format('{0} - {1}', inputs.choice, github.event.workflow_run.head_commit.message) }}
