name: Android - CD

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      environment:
          description: 'Target environment'
          required: false
          default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install node modules
      run: npm i
    
    - name: set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
        
    - name: Load Google Service file
      env:
        DATA: ${{secrets.GOOGLE_SERVICES_JSON}}
      run: echo $DATA | base64 -di > android/app/google-services.json

    - name: TEST
      run: cd android
      
    - name: TEST 2
      run: pwd
      
    - name: build release 
      run: cd android && chmod +x gradlew && ./gradlew assembleRelease
      
    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        groups: Testers
        file: android/app/build/outputs/apk/release/app-release.apk
