name: Android - CI & CD

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      environment:
          description: 'Target environment'
          required: false
          default: 'development'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 21
      uses: actions/setup-java@v1
      with:
        java-version: 21
    - name: Move to /android
      run: cd android
    - name: Load Google Service file
      env:
        DATA: ${{secrets.GOOGLE_SERVICES_JSON}}
      run: echo $DATA | base64 -di > app/google-services.json
    - name: build release 
      run: chmod +x gradlew && ./gradlew assembleRelease
    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        groups: testers
        file: app/build/outputs/apk/release/app-release-unsigned.apk
